import { GoogleGenerativeAI } from '@google/generative-ai';
import { config } from '../config.js';
import * as fs from 'fs/promises';

const genAI = new GoogleGenerativeAI(config.gemini.apiKey);

const PROMPT = `You are an e-commerce garment visualization system. The first image is a garment/clothing item. The second image is a dummy/skeleton/model figure.
Your task: Realistically dress the dummy figure in the garment from the first image.
Requirements:
- Preserve the garment's exact color, pattern, texture, fit, and any logos/prints
- The garment should drape naturally on the dummy's body shape
- Maintain the dummy's pose and background from the second image
- Output only the composite image of the dummy wearing the garment, no additional text`;

export async function generateTryOnImage(
  clothImagePath: string,
  dummyImagePath: string
): Promise<Buffer> {
  const [clothBase64, dummyBase64] = await Promise.all([
    fs.readFile(clothImagePath).then((b) => b.toString('base64')),
    fs.readFile(dummyImagePath).then((b) => b.toString('base64')),
  ]);

  const model = genAI.getGenerativeModel({ model: config.gemini.imageModel });

  const result = await model.generateContent([
    PROMPT,
    {
      inlineData: {
        mimeType: 'image/png',
        data: clothBase64,
      },
    },
    {
      inlineData: {
        mimeType: 'image/png',
        data: dummyBase64,
      },
    },
  ]);

  const response = result.response;
  const imagePart = response.candidates?.[0]?.content?.parts?.find(
    (p) => p.inlineData?.data
  );

  if (!imagePart?.inlineData?.data) {
    throw new Error('No image generated by Gemini');
  }

  return Buffer.from(imagePart.inlineData.data, 'base64');
}